version: '3.9'
services:
  wp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: "./dockerenv/Dockerfile"
    ports:
      - "8000:80"
    volumes:
      - "./web:/var/www/html"
      - "./dockerenv/php.ini:/usr/local/etc/php/conf.d/php.ini"
    links:
      - mailhog:mail
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.1.0-apache
    ports:
      - "8001:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MAX_EXECUTION_TIME: 120
      UPLOAD_LIMIT: 128M

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
    - "8025:8025"
    - "1025:1025"

  db:
    image: mariadb:10.6
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"

volumes:
  db:
